[package]
name = "labonair-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
labonair-theme = { path = "../theme" }
labonair-terminal-integration = { path = "../terminal-integration" }
alacritty_terminal = { workspace = true }
flate2 = "1"
portable-pty = { workspace = true }
tokio = { workspace = true }
labonair-command-palette-core = { path = "../command-palette-core" }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }

[dev-dependencies]
uuid = { workspace = true }
