[package]
name = "labonair-terminal"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = { workspace = true }
labonair-theme = { path = "../theme" }
alacritty_terminal = { workspace = true }
portable-pty = { workspace = true }
tokio = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
