[package]
name = "labonair-hosts"
version = "0.1.0"
edition = "2021"

[dependencies]
labonair-errors = { path = "../errors" }
labonair-persistence = { path = "../persistence" }
labonair-secrets = { path = "../secrets" }
rusqlite = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
