#!/usr/bin/env python3
"""Generate the machine-readable agent route projection."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "agents" / "routes.toml"
OUTPUT = ROOT / "docs" / "generated" / "agent-index.md"


def links(values: list[str]) -> str:
    return "; ".join(f"[`{value}`](../../{value})" for value in values)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE, ROOT / "docs" / "agents" / "routes-schema.md"])
    routes = sorted(data["route"], key=lambda route: route["id"])
    lines = [
        "# Generated Agent Route Index",
        "",
        "<!-- Generated by scripts/gen_agent_index.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "Use [`docs/agents/README.md`](../../docs/agents/README.md) for the human workflow and `AGENTS.md` for binding rules.",
        "",
        "| Route | Request kinds | Required scopes |",
        "| --- | --- | --- |",
    ]
    for route in routes:
        lines.append(f"| **{route['display_name']}** | {', '.join(route['request_kinds'])} | {', '.join(f'`{scope}`' for scope in route['required_scopes'])} |")
    for route in routes:
        lines.extend([
            "",
            f"## {route['display_name']}",
            "",
            f"- First reads: {links(route['first_reads'])}",
            f"- Canonical sources: {links(route['canonical_sources'])}",
            f"- Required scopes: {', '.join(f'`{scope}`' for scope in route['required_scopes'])}",
            f"- Evidence decision: {route['evidence_decision']}",
        ])
    generated = "\n".join(lines) + "\n"
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated agent index: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated agent index is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
