#!/usr/bin/env python3
"""Generate the readable MCP tool catalog."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "automation" / "tools.toml"
OUTPUT = ROOT / "docs" / "generated" / "tools.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE])
    lines = [
        "# Generated MCP Tool Catalog", "",
        "<!-- Generated by scripts/gen_automation.py. Do not edit this file directly. -->", "",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "Source: [`../automation/tools.toml`](../automation/tools.toml).",
        "The catalog is checked against `crates/mcp-server/src/server.rs`.", "",
        "| Tool | Grant | Target | Timeout/limit | Side effects | Negative tests |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for tool in sorted(data["tool"], key=lambda item: item["id"]):
        negatives = "; ".join(tool["negative_tests"])
        lines.append(
            f"| `{tool['id']}` | {tool['required_grant']} | {tool['allowed_targets']} | "
            f"{tool['timeouts_limits']} | {tool['side_effects']} | {negatives} |"
        )
    lines.extend(["", "## Secret and confirmation rules", ""])
    for tool in sorted(data["tool"], key=lambda item: item["id"]):
        lines.append(f"- `{tool['id']}`: {tool['secret_behavior']} Confirmation: {tool['confirmation']}")
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated automation view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated automation view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
