#!/usr/bin/env python3
"""Generate the definition-of-done traceability view from its TOML source."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "reform" / "requirements.toml"
OUTPUT = ROOT / "docs" / "generated" / "reform-coverage.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE])
    records = sorted(data["requirement"], key=lambda record: record["id"])
    lines = [
        "# Generated Documentation Reform Coverage",
        "",
        "<!-- Generated by scripts/gen_reform_coverage.py. Do not edit this file directly. -->",
        "",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "This view is generated from [`../reform/requirements.toml`](../reform/requirements.toml).",
        "It maps every definition-of-done requirement in `docs-reform-plan.md` to its",
        "current status, evidence, limitation, and bounded next task.",
        "",
        "| ID | Plan section | Status | Owner | Requirement | Evidence | Limitation | Next task |",
        "| --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for record in records:
        next_task = record["next_task"]
        lines.append(
            f"| `{record['id']}` | `{record['plan_section']}` | **{record['status']}** | "
            f"{record['owner']} | {record['requirement']} | {'; '.join(record['evidence'])} | "
            f"{record['limitation']} | [`{next_task}`](../../{next_task}) |"
        )
    lines.extend(["", "## Source references", ""])
    for record in records:
        refs = "; ".join(f"`{reference}`" for reference in record["source_refs"])
        lines.append(f"- `{record['id']}`: {refs}")
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated reform coverage: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated reform coverage is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
