#!/usr/bin/env python3
"""Generate the readable native release checklist."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "release" / "checklist.toml"
OUTPUT = ROOT / "docs" / "generated" / "release.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE, ROOT / "docs" / "release" / "checklist-schema.md"])
    checks = sorted(data["check"], key=lambda item: item["id"])
    lines = [
        "# Generated Release Checklist",
        "",
        "<!-- Generated by scripts/gen_release.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "| ID | Area | Owner | Status | Command |",
        "| --- | --- | --- | --- | --- |",
    ]
    for check in checks:
        lines.append(f"| `{check['id']}` | {check['area']} | `{check['owner']}` | `{check['status']}` | `{check['command']}` |")
    lines.extend(["", "## Handoff records", ""])
    for check in checks:
        lines.extend([
            f"### {check['id']}",
            "",
            f"- Evidence: {'; '.join(check['evidence'])}",
            f"- Limitation: {check['limitation']}",
            f"- Next action: {check['next_action']}",
            "",
        ])
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated release view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated release view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
