#!/usr/bin/env python3
"""Generate command, surface, and menu catalog views."""

from __future__ import annotations

import argparse
from pathlib import Path
import tomllib

from architecture_model import ROOT, source_fingerprint


PRODUCT_DIR = ROOT / "docs" / "product"
OUTPUT_DIR = ROOT / "docs" / "generated"


def load(name: str) -> dict:
    return tomllib.loads((PRODUCT_DIR / name).read_text(encoding="utf-8"))


def render_commands(data: dict, fingerprint: str) -> str:
    lines = [
        "# Generated Command Catalog", "",
        "<!-- Generated by scripts/gen_product_catalog.py. Do not edit this file directly. -->", "",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "Stable command IDs are defined by `CommandId`; ownership and evidence",
        "come from [`../product/commands.toml`](../product/commands.toml).", "",
        "| Group | Owner | Canonical crate | Menu path | Commands | Visual evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for group in sorted(data["group"], key=lambda item: item["id"]):
        ids = ", ".join(f"`{identifier}`" for identifier in group["ids"])
        evidence = "; ".join(group["visual_evidence"])
        lines.append(
            f"| `{group['id']}` | `{group['owner_module']}` | `{group['canonical_crate']}` | "
            f"{group['menu_path']} | {ids} | {evidence} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_surfaces(data: dict, fingerprint: str) -> str:
    lines = [
        "# Generated Surface Catalog", "",
        "<!-- Generated by scripts/gen_product_catalog.py. Do not edit this file directly. -->", "",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "Canonical product surfaces are defined by [`../product/surfaces.toml`](../product/surfaces.toml).", "",
        "| Surface | Owner | Kind | Entry points | Commands | Status | Evidence |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for surface in sorted(data["surface"], key=lambda item: item["id"]):
        entries = "; ".join(surface["canonical_entry_points"])
        commands = ", ".join(f"`{identifier}`" for identifier in surface["command_ids"])
        evidence = "; ".join(surface["evidence"])
        lines.append(
            f"| `{surface['id']}` | `{surface['owner_module']}` | `{surface['kind']}` | {entries} | "
            f"{commands} | `{surface['status']}` | {evidence} |"
        )
    lines.append("")
    return "\n".join(lines)


def render_menu(data: dict, fingerprint: str) -> str:
    lines = [
        "# Generated Menu Catalog", "",
        "<!-- Generated by scripts/gen_product_catalog.py. Do not edit this file directly. -->", "",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "The global menu model is defined by [`../product/menu.toml`](../product/menu.toml).", "",
        "| Menu branch | Label | Owner | Canonical surface | Commands | Evidence |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for menu in sorted(data["menu"], key=lambda item: item["id"]):
        commands = ", ".join(f"`{identifier}`" for identifier in menu["command_ids"])
        evidence = "; ".join(menu["evidence"])
        lines.append(
            f"| `{menu['id']}` | {menu['label']} | `{menu['owner_module']}` | "
            f"`{menu['canonical_surface']}` | {commands} | {evidence} |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated views are stale")
    args = parser.parse_args()
    source_paths = [PRODUCT_DIR / "commands.toml", PRODUCT_DIR / "surfaces.toml", PRODUCT_DIR / "menu.toml"]
    fingerprint = source_fingerprint(source_paths)
    outputs = {
        "commands.md": render_commands(load("commands.toml"), fingerprint),
        "surfaces.md": render_surfaces(load("surfaces.toml"), fingerprint),
        "menu.md": render_menu(load("menu.toml"), fingerprint),
    }
    for name, generated in outputs.items():
        output = OUTPUT_DIR / name
        if args.check:
            current = output.read_text(encoding="utf-8") if output.exists() else None
            if current != generated:
                print(f"stale generated product view: {output.relative_to(ROOT)}")
                return 1
        else:
            OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
            output.write_text(generated, encoding="utf-8")
    if args.check:
        print("generated product catalog views are fresh")
    else:
        print("generated docs/generated/commands.md, surfaces.md, and menu.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
