#!/usr/bin/env python3
"""Generate the readable capability index from structured descriptors."""

from __future__ import annotations

import argparse
from pathlib import Path
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE_DIR = ROOT / "docs" / "capabilities"
OUTPUT = ROOT / "docs" / "generated" / "capabilities.md"


def load_descriptors() -> list[dict]:
    result = []
    for path in sorted(SOURCE_DIR.glob("*.toml")):
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        if "capability" not in data:
            continue
        result.append({"path": path, **data["capability"], "evidence": data["evidence"]})
    return sorted(result, key=lambda item: item["id"])


def descriptor_paths() -> list[Path]:
    paths = []
    for path in sorted(SOURCE_DIR.glob("*.toml")):
        data = tomllib.loads(path.read_text(encoding="utf-8"))
        if "capability" in data:
            paths.append(path)
    return paths


def inline(items: list[str]) -> str:
    return "; ".join(items) if items else "none"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed projection differs from generated output",
    )
    args = parser.parse_args()
    descriptors = load_descriptors()
    fingerprint = source_fingerprint(descriptor_paths())
    lines = [
        "# Generated Capability Index",
        "",
        "<!-- Generated by scripts/gen_capabilities.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "This view is generated from [`../capabilities/`](../capabilities/) and",
        "validated by `python3 scripts/check_capabilities.py`. The descriptor",
        "schema is [`../capabilities/schema.md`](../capabilities/schema.md); the",
        "top-level matrix remains [`../capabilities.md`](../capabilities.md).",
        "",
        "| Capability | Owner | Canonical crate | Current | Target | Entry points |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for item in descriptors:
        entries = "; ".join(item["canonical_entry_points"])
        lines.append(
            f"| **{item['display_name']}** | `{item['owner_module']}` | "
            f"`{item['canonical_crate']}` | `{item['current_status']}` | "
            f"`{item['target_status']}` | {entries} |"
        )

    for item in descriptors:
        lines.extend(
            [
                "",
                f"## {item['display_name']}",
                "",
                f"- Descriptor: [`{item['path'].name}`](../capabilities/{item['path'].name})",
                f"- Owner: `{item['owner_module']}`",
                f"- Canonical crate: `{item['canonical_crate']}`",
                f"- Siblings: {inline([f'`{value}`' for value in item['sibling_crates']])}",
                f"- Current/target: `{item['current_status']}` → `{item['target_status']}`",
                f"- Entry points: {inline(item['canonical_entry_points'])}",
                f"- Commands: {inline([f'`{value}`' for value in item['commands']])}",
                f"- State: {item['state_owner']}",
                f"- Persistence: {item['persistence_owner']}",
                f"- Visual states: {inline(item['visual_states'])}",
                f"- Known limitations: {inline(item['known_limitations'])}",
                "",
                "Evidence:",
            ]
        )
        for category in sorted(item["evidence"]):
            lines.append(f"- `{category}`: {inline(item['evidence'][category])}")

    lines.append("")
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated capability view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated capability view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
