#!/usr/bin/env python3
"""Generate the readable scorecard from its structured source."""

from __future__ import annotations

import argparse
from pathlib import Path
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "evidence" / "scorecard.toml"
OUTPUT = ROOT / "docs" / "generated" / "scorecard.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE])
    items = sorted(data["item"], key=lambda item: item["id"])
    lines = [
        "# Generated Labonair Scorecard", "",
        "<!-- Generated by scripts/gen_scorecard.py. Do not edit this file directly. -->", "",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "This view is generated from [`../evidence/scorecard.toml`](../evidence/scorecard.toml).",
        "Statuses are evidence states, not implementation promises.", "",
        "| ID | Area | Owner | Status | Target | Limitation | Next action |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in items:
        lines.append(
            f"| `{item['id']}` | {item['area']} | `{item['owner']}` | **{item['status']}** | "
            f"{item['target']} | {item['limitation']} | {item['next_action']} |"
        )
    lines.extend(["", "## Evidence references", ""])
    for item in items:
        refs = "; ".join(f"`{reference}`" for reference in item["source_refs"])
        lines.append(f"- `{item['id']}`: {refs}")
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated scorecard: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated scorecard is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
