#!/usr/bin/env python3
"""Generate a readable architecture inventory from the policy manifest."""

from __future__ import annotations

import argparse
from pathlib import Path

from architecture_model import ROOT, load_manifest, manifest_graph, source_fingerprint


OUTPUT = ROOT / "docs" / "generated" / "architecture.md"


def cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed projection differs from generated output",
    )
    args = parser.parse_args()
    manifest = load_manifest()
    graph = manifest_graph(manifest)
    fingerprint = source_fingerprint([ROOT / "docs" / "architecture" / "graph.toml"])
    crates = {crate["name"]: crate for crate in manifest["crate"]}
    policy = manifest["policy"]

    lines = [
        "# Generated Architecture Inventory",
        "",
        "<!-- Generated by scripts/gen_architecture.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "This is a human-readable projection of the normative policy source",
        "[`../architecture/graph.toml`](../architecture/graph.toml). The policy",
        "source and [`../architecture.md`](../architecture.md) remain authoritative.",
        "",
        f"- Manifest version: `{manifest['version']}`",
        f"- Composition roots: {', '.join(f'`{name}`' for name in policy['composition_roots'])}",
        f"- UI kit: `{policy['ui_kit']}`",
        f"- Active queue: [`{policy['active_queue']}`](../../{policy['active_queue']})",
        f"- Workspace crates: {len(crates)}",
        f"- Internal dependency edges: {sum(len(dependencies) for dependencies in graph.values())}",
        "",
        "## Ownership and layer",
        "",
        "| Crate | Owner | Role | Layer | Direct workspace dependencies |",
        "| --- | --- | --- | --- | --- |",
    ]
    for name in sorted(crates):
        crate = crates[name]
        dependencies = ", ".join(f"`{dependency}`" for dependency in sorted(graph[name])) or "—"
        lines.append(
            f"| `{cell(name)}` | `{cell(crate['owner'])}` | `{cell(crate['role'])}` | "
            f"`{cell(crate['layer'])}` | {dependencies} |"
        )

    lines.extend(
        [
            "",
            "## Transitional edges",
            "",
            "Every compatibility edge has a removal condition. It remains visible",
            "here so agents do not mistake a tolerated edge for a target dependency.",
            "",
            "| From | To | Status | Removal condition |",
            "| --- | --- | --- | --- |",
        ]
    )
    for transition in manifest.get("transitional_edge", []):
        lines.append(
            f"| `{cell(transition['from'])}` | `{cell(transition['to'])}` | "
            f"`{cell(transition['status'])}` | {cell(transition['removal_condition'])} |"
        )

    lines.extend(
        [
            "",
            "## Update protocol",
            "",
            "1. Change the owning crate contract and implementation task first.",
            "2. Update `docs/architecture/graph.toml` and the relevant audit or ADR.",
            "3. Run `python3 scripts/verify.py --scope architecture`.",
            "4. Regenerate this view with `python3 scripts/gen_architecture.py`.",
            "",
        ]
    )
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated architecture view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated architecture view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
