#!/usr/bin/env python3
"""Generate the readable Settings lifecycle and field index."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "settings" / "catalog.toml"
AREAS_SOURCE = ROOT / "crates" / "settings-content" / "src" / "areas.rs"
CONTENT_SOURCE = ROOT / "crates" / "settings-content" / "src" / "settings_content.rs"
FIELD_SOURCE = ROOT / "crates" / "settings-ui" / "src" / "schema.rs"
OUTPUT = ROOT / "docs" / "generated" / "settings.md"
FIELD_CALL = re.compile(
    r"\bfield(?:_with_details)?!\(\s*([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*),\s*\"([^\"]+)\""
)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fields = sorted(
        {f"{area}.{json_field}" for area, _, json_field in FIELD_CALL.findall(FIELD_SOURCE.read_text(encoding="utf-8"))}
    )
    areas = {area["id"]: area for area in data["area"]}
    fingerprint = source_fingerprint([SOURCE, AREAS_SOURCE, CONTENT_SOURCE, FIELD_SOURCE, ROOT / data["inventory_source"]])
    lines = [
        "# Generated Settings Catalog",
        "",
        "<!-- Generated by scripts/gen_settings.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "This view combines the structured lifecycle source with the native field registry.",
        "Field-level keep/move/remove decisions remain in [`../settings-inventory.md`](../settings-inventory.md).",
        "",
        "| Area | Owner | Scope | Status | Field count | Entry point |",
        "| --- | --- | --- | --- | ---: | --- |",
    ]
    for identifier in sorted(areas):
        area = areas[identifier]
        count = sum(path.startswith(f"{identifier}.") for path in fields)
        lines.append(
            f"| **{area['display_name']}** | `{area['canonical_crate']}` | "
            f"{', '.join(area['scopes'])} | `{area['status']}` | {count} | {area['entry_point']} |"
        )
    lines.extend(["", "## Area lifecycle records", ""])
    for identifier in sorted(areas):
        area = areas[identifier]
        area_fields = [path for path in fields if path.startswith(f"{identifier}.")]
        lines.extend([
            f"### {area['display_name']}",
            "",
            f"- Native target module: `{area['target_module']}`",
            f"- Storage: {area['storage']}",
            f"- Migration: {area['migration']}",
            f"- Reload: {area['reload']}",
            f"- Secret classification: {area['secret_classification']}",
            f"- Source/tests: {', '.join(f'`{value}`' for value in area['source_files'] + area['tests'])}",
            f"- Registered UI fields ({len(area_fields)}): {', '.join(f'`{value}`' for value in area_fields)}",
            "",
        ])
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated Settings view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated Settings view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
