#!/usr/bin/env python3
"""Generate the readable end-to-end workflow catalog."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "product" / "workflows.toml"
OUTPUT = ROOT / "docs" / "generated" / "workflows.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE])
    workflows = sorted(data["workflow"], key=lambda item: item["id"])
    lines = [
        "# Generated Workflow Catalog", "",
        "<!-- Generated by scripts/gen_workflows.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "Source: [`../product/workflows.toml`](../product/workflows.toml).",
        "Each record connects user entry, state, persistence, failure, security, and evidence.", "",
        "| Workflow | Owner | Entry point | Commands | Status | Next task | Next action |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for workflow in workflows:
        commands = ", ".join(f"`{command}`" for command in workflow["commands"])
        lines.append(
            f"| `{workflow['id']}` | `{workflow['owner_module']}` | {workflow['entry_point']} | "
            f"{commands} | `{workflow['status']}` | [`{workflow['next_task']}`](../../{workflow['next_task']}) | {workflow['next_action']} |"
        )
    lines.extend(["", "## State and failure coverage", ""])
    for workflow in workflows:
        states = "; ".join(workflow["state_transitions"])
        failures = "; ".join(workflow["failure_modes"])
        lines.append(f"- `{workflow['id']}` — states: {states}; failures: {failures}")
    generated = "\n".join(lines) + "\n"
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated workflow view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated workflow view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
