#!/usr/bin/env python3
"""Render the workspace-internal crate graph.

Reads `cargo metadata --format-version 1 --no-deps` on stdin and writes:

  * docs/assets/crate-graph.dot   — Graphviz source (regenerate the SVG with
    `dot -Tsvg` if Graphviz is installed)
  * docs/assets/crate-graph.svg   — a self-contained tiered SVG (no Graphviz
    dependency; nodes are layered by longest-path depth)

Also prints a Markdown adjacency list on stdout for docs/architecture.md.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASSETS = ROOT / "docs" / "assets"

meta = json.load(sys.stdin)

graph = {}
for pkg in meta["packages"]:
    name = pkg["name"]
    if not name.startswith("labonair"):
        continue
    graph[name] = sorted({
        d["name"] for d in pkg["dependencies"]
        if d["name"].startswith("labonair") and d["name"] != name
    })

nodes = sorted(graph)

# ---------------------------------------------------------------------------
# DOT
# ---------------------------------------------------------------------------
dot = ["digraph labonair_crates {", '  rankdir=TB;',
       '  node [shape=box, style=rounded, fontname="Helvetica", fontsize=10];',
       '  edge [color="#888888"];', ""]
for n in nodes:
    for dep in graph[n]:
        dot.append(f'  "{n}" -> "{dep}";')
dot.append("}")
ASSETS.mkdir(parents=True, exist_ok=True)
(ASSETS / "crate-graph.dot").write_text("\n".join(dot) + "\n")

# ---------------------------------------------------------------------------
# Tiered SVG — depth = longest path to a leaf (leaves at the bottom).
# ---------------------------------------------------------------------------
_depth = {}
def depth(n):
    if n in _depth:
        return _depth[n]
    _depth[n] = 0  # guard (graph is acyclic; check-crate-deps.sh enforces it)
    d = 1 + max((depth(c) for c in graph[n]), default=-1)
    _depth[n] = d
    return d

for n in nodes:
    depth(n)

tiers = {}
for n in nodes:
    tiers.setdefault(depth(n), []).append(n)
for d in tiers:
    tiers[d].sort()

max_depth = max(tiers)
BOX_W, BOX_H = 190, 34
GAP_X, GAP_Y = 24, 90
MARGIN = 30
row_width = max(len(v) for v in tiers.values())
width = MARGIN * 2 + row_width * (BOX_W + GAP_X) - GAP_X
height = MARGIN * 2 + (max_depth + 1) * (BOX_H + GAP_Y) - GAP_Y

pos = {}
for d, members in tiers.items():
    row = max_depth - d  # leaves (d=0) -> bottom row
    y = MARGIN + row * (BOX_H + GAP_Y)
    total = len(members) * (BOX_W + GAP_X) - GAP_X
    x0 = MARGIN + (width - MARGIN * 2 - total) / 2
    for i, n in enumerate(members):
        x = x0 + i * (BOX_W + GAP_X)
        pos[n] = (x, y)

svg = [
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
    f'height="{height}" viewBox="0 0 {width} {height}" '
    f'font-family="Helvetica, Arial, sans-serif" font-size="11">',
    '<style>'
    '.n{fill:#f5f5f7;stroke:#c8102e;stroke-width:1.2}'
    '.t{fill:#1d1d1f;text-anchor:middle;dominant-baseline:middle}'
    '.e{stroke:#9aa0a6;stroke-width:1;fill:none;marker-end:url(#a)}'
    '</style>',
    '<defs><marker id="a" viewBox="0 0 10 10" refX="9" refY="5" '
    'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
    '<path d="M0 0 L10 5 L0 10 z" fill="#9aa0a6"/></marker></defs>',
    f'<rect width="{width}" height="{height}" fill="white"/>',
]

def anchor(n, toward):
    x, y = pos[n]
    cx, cy = x + BOX_W / 2, y + BOX_H / 2
    tx, ty = toward
    # exit from bottom edge if target is below, else top edge
    if ty > cy:
        return cx, y + BOX_H
    return cx, y

for n in nodes:
    for dep in graph[n]:
        sx_c, sy_c = pos[n][0] + BOX_W / 2, pos[n][1] + BOX_H / 2
        dx_c, dy_c = pos[dep][0] + BOX_W / 2, pos[dep][1] + BOX_H / 2
        sx, sy = anchor(n, (dx_c, dy_c))
        dx, dy = anchor(dep, (sx_c, sy_c))
        svg.append(f'<path class="e" d="M{sx:.1f} {sy:.1f} L{dx:.1f} {dy:.1f}"/>')

for n in nodes:
    x, y = pos[n]
    svg.append(
        f'<rect class="n" x="{x:.1f}" y="{y:.1f}" width="{BOX_W}" '
        f'height="{BOX_H}" rx="6"/>'
    )
    svg.append(
        f'<text class="t" x="{x + BOX_W / 2:.1f}" y="{y + BOX_H / 2:.1f}">'
        f'{n}</text>'
    )

svg.append("</svg>")
(ASSETS / "crate-graph.svg").write_text("\n".join(svg) + "\n")

# ---------------------------------------------------------------------------
# Markdown adjacency list (stdout)
# ---------------------------------------------------------------------------
print(f"<!-- generated by scripts/gen-crate-graph.sh — do not edit by hand -->")
print(f"{len(nodes)} workspace crates, "
      f"{sum(len(v) for v in graph.values())} internal edges, "
      f"{max_depth + 1} tiers.\n")
for n in nodes:
    deps = ", ".join(f"`{d}`" for d in graph[n]) or "*(leaf)*"
    print(f"- `{n}` → {deps}")
