#!/usr/bin/env python3
"""Generate the readable performance budget view."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "performance" / "budgets.toml"
OUTPUT = ROOT / "docs" / "generated" / "performance.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when output is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE, ROOT / "docs" / "performance" / "catalog-schema.md"])
    lines = [
        "# Generated Performance Budget Catalog",
        "",
        "<!-- Generated by scripts/gen_performance.py. Do not edit this file directly. -->",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "Targets and evidence are sourced from [`../performance/budgets.toml`](../performance/budgets.toml).",
        "",
        "| ID | Area | Owner | Status | Target |",
        "| --- | --- | --- | --- | --- |",
    ]
    for budget in sorted(data["budget"], key=lambda item: item["id"]):
        lines.append(f"| `{budget['id']}` | {budget['area']} | `{budget['owner']}` | `{budget['status']}` | {budget['target']} |")
    lines.extend(["", "## Measurement records", ""])
    for budget in sorted(data["budget"], key=lambda item: item["id"]):
        lines.extend([
            f"### {budget['id']}",
            "",
            f"- Measurement: {budget['measurement']}",
            f"- Environment: {budget['environment']}",
            f"- Evidence: {'; '.join(budget['evidence'])}",
            f"- Limitation: {budget['limitation']}",
            f"- Next action: {budget['next_action']}",
            "",
        ])
    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated performance view: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated performance view is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
