#!/usr/bin/env python3
"""Generate the deterministic per-surface visual evidence index."""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "testing" / "visual-evidence.toml"
SURFACES = ROOT / "docs" / "product" / "surfaces.toml"
OUTPUT = ROOT / "docs" / "generated" / "visual-evidence.md"


def slug(value: str) -> str:
    result = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return result or "state"


def expected_artifact(data: dict, surface_id: str, state: str) -> str:
    filename = data["artifact_name_pattern"].format(
        surface_id=slug(surface_id),
        state_slug=slug(state),
        viewport=data["default_viewport"],
        platform=data["default_platform"],
        commit="<commit>",
    )
    return f"{data['artifact_root']}/{filename}"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    surfaces = tomllib.loads(SURFACES.read_text(encoding="utf-8"))["surface"]
    captures = {
        (capture["surface_id"], capture["state"], capture["platform"], capture["viewport"]): capture
        for capture in data.get("capture", [])
    }
    fingerprint = source_fingerprint([SOURCE, SURFACES])
    lines = [
        "# Generated Visual Evidence Index",
        "",
        "<!-- Generated by scripts/gen_visual_evidence.py. Do not edit this file directly. -->",
        "",
        f"<!-- Source fingerprint: `{fingerprint}` -->",
        "",
        "This per-surface screenshot index is generated from [`../testing/visual-evidence.toml`](../testing/visual-evidence.toml) and the canonical surface catalog.",
        "A pending path is an expected future artifact, not evidence that a screenshot exists.",
        "",
        f"**Environment:** `{data['environment_status']}` — {data['environment_blocker']}",
        "",
        f"**Naming pattern:** `{data['artifact_name_pattern']}`",
        "",
        "| Surface | Owner | Overall status | States | Index | Next action |",
        "| --- | --- | --- | ---: | --- | --- |",
    ]
    for surface in sorted(surfaces, key=lambda item: item["id"]):
        record = next(item for item in data["surface"] if item["id"] == surface["id"])
        statuses = set(record["state_status"].values())
        if statuses == {"N/A"}:
            overall = "N/A"
        elif statuses <= {"Verified", "N/A"} and "Verified" in statuses:
            overall = "Verified"
        elif "Partial" in statuses or "Verified" in statuses or "N/A" in statuses:
            overall = "Partial"
        else:
            overall = "Pending"
        anchor = f"surface-{slug(surface['id'])}"
        lines.append(
            f"| `{surface['id']}` | `{surface['owner_module']}` | **{overall}** | "
            f"{len(surface['visual_states'])} | [state index](#{anchor}) | {record['next_action']} |"
        )

    lines.extend(["", "## Capture protocol", "", "1. Launch `cargo run -p labonair` or the exact packaged native executable.",
                   "2. Resolve the exact native PID and layer-0 window before capture.",
                   "3. Use the catalog state label and the deterministic artifact path.",
                   "4. Add a `capture` record only after the artifact is retained in the repository artifact store.",
                   "5. Keep the state `Pending` when the supported host or capture permission is unavailable.", ""])

    for surface in sorted(surfaces, key=lambda item: item["id"]):
        record = next(item for item in data["surface"] if item["id"] == surface["id"])
        anchor = f"surface-{slug(surface['id'])}"
        lines.extend([
            f'<a id="{anchor}"></a>',
            f"## Surface: `{surface['id']}` — {surface['display_name']}",
            "",
            f"Owner: `{surface['owner_module']}` · Canonical crate: `{surface['canonical_crate']}` · Context: {surface['context']}",
            "",
            "| Catalog state | Status | Expected artifact | Capture record |",
            "| --- | --- | --- | --- |",
        ])
        for state in surface["visual_states"]:
            status = record["state_status"][state]
            capture = next(
                (
                    item for key, item in captures.items()
                    if key[0] == surface["id"] and key[1] == state
                    and key[2] == data["default_platform"] and key[3] == data["default_viewport"]
                ),
                None,
            )
            if capture:
                artifact = capture["artifact"]
                capture_text = f"`{capture['binary']}` · PID `{capture['pid']}` · window `{capture['window']}` · {capture['captured_at']}"
                artifact_text = f"[`{artifact}`](../../{artifact})"
            elif status == "N/A":
                artifact_text = "`N/A`"
                capture_text = "Reason required in source"
            else:
                artifact = expected_artifact(data, surface["id"], state)
                artifact_text = f"`{artifact}`"
                capture_text = "Pending — no accepted native capture"
            lines.append(f"| `{state}` | **{status}** | {artifact_text} | {capture_text} |")
        lines.extend(["", f"Next action: {record['next_action']}", ""])

    generated = "\n".join(lines)
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated visual evidence index: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated visual evidence index is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
