#!/usr/bin/env python3
"""Generate the complete capability coverage projection."""

from __future__ import annotations

import argparse
import tomllib

from architecture_model import ROOT, source_fingerprint


SOURCE = ROOT / "docs" / "capabilities" / "coverage.toml"
OUTPUT = ROOT / "docs" / "generated" / "capability-coverage.md"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when the generated view is stale")
    args = parser.parse_args()
    data = tomllib.loads(SOURCE.read_text(encoding="utf-8"))
    fingerprint = source_fingerprint([SOURCE])
    entries = sorted(data["coverage"]["capability"], key=lambda item: item["id"])
    lines = [
        "# Generated Capability Coverage", "",
        "<!-- Generated by scripts/gen_capability_coverage.py. Do not edit this file directly. -->", "",
        f"<!-- Source fingerprint: `{fingerprint}` -->", "",
        "This view covers every row in [`../capabilities.md`](../capabilities.md).",
        "Pilot descriptors are linked; remaining rows carry an explicit next action.", "",
        "| Capability | Owner | Canonical crate | Coverage | Descriptor | Next action |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        descriptor = entry["descriptor_file"]
        link = "none" if descriptor == "none" else f"[`{descriptor}`](../capabilities/{descriptor})"
        lines.append(
            f"| {entry['display_name']} | `{entry['owner_module']}` | `{entry['canonical_crate']}` | "
            f"`{entry['coverage_status']}` | {link} | {entry['next_action']} |"
        )
    generated = "\n".join(lines) + "\n"
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"stale generated capability coverage: {OUTPUT.relative_to(ROOT)}")
            return 1
        print(f"generated capability coverage is fresh: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
