[package]
name = "labonair-snippets"
version = "0.1.0"
edition = "2021"

[dependencies]
labonair-errors = { path = "../errors" }
labonair-persistence = { path = "../persistence" }
rusqlite = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
libc = "0.2"

[dev-dependencies]
