[package]
name = "labonair-notifications"
version = "0.1.0"
edition = "2021"

[lib]
name = "labonair_notifications"
path = "src/notifications.rs"

[dependencies]
gpui = { workspace = true }
labonair-notifications-core = { path = "../notifications-core" }

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }
